<?php

use Illuminate\Database\Seeder;

class EducationSpecializationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement("SET FOREIGN_KEY_CHECKS=0;");
        DB::table("education_specialization")->truncate();

        $data = array(

        	array('id' =>1, 'education_qualification_id' => 1, 'name' => 'Other'),
			array('id' =>2, 'education_qualification_id' => 1, 'name' => 'ALTP'),
			array('id' =>3, 'education_qualification_id' => 1, 'name' => 'Commercial Pilot Licence (CPL)'),
			array('id' =>4, 'education_qualification_id' => 1, 'name' => 'Private Pilot License (PPL)'),
			array('id' =>5, 'education_qualification_id' => 2, 'name' => 'Other'),
			array('id' =>6, 'education_qualification_id' => 2, 'name' => 'Arts & Humanities'),
			array('id' =>7, 'education_qualification_id' => 2, 'name' => 'Communication'),
			array('id' =>8, 'education_qualification_id' => 2, 'name' => 'Economics'),
			array('id' =>9, 'education_qualification_id' => 2, 'name' => 'English'),
			array('id' =>10, 'education_qualification_id' => 2, 'name' => 'Film'),
			array('id' =>11, 'education_qualification_id' => 2, 'name' => 'Fine Arts'),
			array('id' =>12, 'education_qualification_id' => 2, 'name' => 'General'),
			array('id' =>13, 'education_qualification_id' => 2, 'name' => 'Hindi'),
			array('id' =>14, 'education_qualification_id' => 2, 'name' => 'History'),
			array('id' =>15, 'education_qualification_id' => 2, 'name' => 'Journalism'),
			array('id' =>16, 'education_qualification_id' => 2, 'name' => 'Literature'),
			array('id' =>17, 'education_qualification_id' => 2, 'name' => 'Mathematics'),
			array('id' =>18, 'education_qualification_id' => 2, 'name' => 'Philosophy'),
			array('id' =>19, 'education_qualification_id' => 2, 'name' => 'Political Science'),
			array('id' =>20, 'education_qualification_id' => 2, 'name' => 'PR/Advertising'),
			array('id' =>21, 'education_qualification_id' => 2, 'name' => 'Psychology'),
			array('id' =>22, 'education_qualification_id' => 2, 'name' => 'Sanskrit'),
			array('id' =>23, 'education_qualification_id' => 2, 'name' => 'Sociology'),
			array('id' =>24, 'education_qualification_id' => 2, 'name' => 'Statistics'),
			array('id' =>25, 'education_qualification_id' => 2, 'name' => 'Vocational Courses'),
			array('id' =>26, 'education_qualification_id' => 2, 'name' => 'Other Arts'),
			array('id' =>27, 'education_qualification_id' => 3, 'name' => 'Architecture'),
			array('id' =>28, 'education_qualification_id' => 4, 'name' => 'Management'),
			array('id' =>29, 'education_qualification_id' => 5, 'name' => 'Computers'),
			array('id' =>30, 'education_qualification_id' => 6, 'name' => 'Commerce'),
			array('id' =>31, 'education_qualification_id' => 7, 'name' => 'Dental'),
			array('id' =>32, 'education_qualification_id' => 8, 'name' => 'Other'),
			array('id' =>33, 'education_qualification_id' => 8, 'name' => 'Agriculture'),
			array('id' =>34, 'education_qualification_id' => 8, 'name' => 'Automobile'),
			array('id' =>35, 'education_qualification_id' => 8, 'name' => 'Aviation/Aeronautical'),
			array('id' =>36, 'education_qualification_id' => 8, 'name' => 'Bio-Chemistry/Bio-Technology'),
			array('id' =>37, 'education_qualification_id' => 8, 'name' => 'Biomedical'),
			array('id' =>38, 'education_qualification_id' => 8, 'name' => 'Ceramics'),
			array('id' =>39, 'education_qualification_id' => 8, 'name' => 'Chemical'),
			array('id' =>40, 'education_qualification_id' => 8, 'name' => 'Civil'),
			array('id' =>41, 'education_qualification_id' => 8, 'name' => 'Computers'),
			array('id' =>42, 'education_qualification_id' => 8, 'name' => 'Cosmetics'),
			array('id' =>43, 'education_qualification_id' => 8, 'name' => 'Cosmetology'),
			array('id' =>44, 'education_qualification_id' => 8, 'name' => 'Electrical'),
			array('id' =>45, 'education_qualification_id' => 8, 'name' => 'Electronics/Telecommunications'),
			array('id' =>46, 'education_qualification_id' => 8, 'name' => 'Energy'),
			array('id' =>47, 'education_qualification_id' => 8, 'name' => 'Engineering Physics'),
			array('id' =>48, 'education_qualification_id' => 8, 'name' => 'Environmental science'),
			array('id' =>49, 'education_qualification_id' => 8, 'name' => 'Instrumentation'),
			array('id' =>50, 'education_qualification_id' => 8, 'name' => 'Marine'),
			array('id' =>51, 'education_qualification_id' => 8, 'name' => 'Material Technology'),
			array('id' =>52, 'education_qualification_id' => 8, 'name' => 'Mechanical'),
			array('id' =>53, 'education_qualification_id' => 8, 'name' => 'Metallurgy'),
			array('id' =>54, 'education_qualification_id' => 8, 'name' => 'Mineral'),
			array('id' =>55, 'education_qualification_id' => 8, 'name' => 'Mining'),
			array('id' =>56, 'education_qualification_id' => 8, 'name' => 'Nuclear'),
			array('id' =>57, 'education_qualification_id' => 8, 'name' => 'Paint/Oil'),
			array('id' =>58, 'education_qualification_id' => 8, 'name' => 'Petroleum'),
			array('id' =>59, 'education_qualification_id' => 8, 'name' => 'Plastics'),
			array('id' =>60, 'education_qualification_id' => 8, 'name' => 'Production/Industrial'),
			array('id' =>61, 'education_qualification_id' => 8, 'name' => 'Textile'),
			array('id' =>62, 'education_qualification_id' => 8, 'name' => 'Other Engineering'),
			array('id' =>63, 'education_qualification_id' => 9, 'name' => 'Education'),
			array('id' =>64, 'education_qualification_id' => 10, 'name' => 'Medicine'),
			array('id' =>65, 'education_qualification_id' => 11, 'name' => 'Hotel Management'),
			array('id' =>66, 'education_qualification_id' => 12, 'name' => 'Medicine'),
			array('id' =>67, 'education_qualification_id' => 13, 'name' => 'Law'),
			array('id' =>68, 'education_qualification_id' => 14, 'name' => 'Pharmacy'),
			array('id' =>69, 'education_qualification_id' => 15, 'name' => 'Other'),
			array('id' =>70, 'education_qualification_id' => 15, 'name' => 'Agriculture'),
			array('id' =>71, 'education_qualification_id' => 15, 'name' => 'Anthropology'),
			array('id' =>72, 'education_qualification_id' => 15, 'name' => 'Bio-Chemistry/Bio-Technology'),
			array('id' =>73, 'education_qualification_id' => 15, 'name' => 'Biology'),
			array('id' =>74, 'education_qualification_id' => 15, 'name' => 'Botany'),
			array('id' =>75, 'education_qualification_id' => 15, 'name' => 'Chemistry'),
			array('id' =>76, 'education_qualification_id' => 15, 'name' => 'Computers'),
			array('id' =>77, 'education_qualification_id' => 15, 'name' => 'Cosmetics'),
			array('id' =>78, 'education_qualification_id' => 15, 'name' => 'Cosmetology'),
			array('id' =>79, 'education_qualification_id' => 15, 'name' => 'Dairy Technology'),
			array('id' =>80, 'education_qualification_id' => 15, 'name' => 'Electronics'),
			array('id' =>81, 'education_qualification_id' => 15, 'name' => 'Environmental science'),
			array('id' =>82, 'education_qualification_id' => 15, 'name' => 'Food Technology'),
			array('id' =>83, 'education_qualification_id' => 15, 'name' => 'General'),
			array('id' =>84, 'education_qualification_id' => 15, 'name' => 'Geology'),
			array('id' =>85, 'education_qualification_id' => 15, 'name' => 'Home science'),
			array('id' =>86, 'education_qualification_id' => 15, 'name' => 'IT'),
			array('id' =>87, 'education_qualification_id' => 15, 'name' => 'Mathematics'),
			array('id' =>88, 'education_qualification_id' => 15, 'name' => 'Microbiology'),
			array('id' =>89, 'education_qualification_id' => 15, 'name' => 'Nursing'),
			array('id' =>90, 'education_qualification_id' => 15, 'name' => 'Physics'),
			array('id' =>91, 'education_qualification_id' => 15, 'name' => 'Statistics'),
			array('id' =>92, 'education_qualification_id' => 15, 'name' => 'Anesthesiology'),
			array('id' =>93, 'education_qualification_id' => 15, 'name' => 'Zoology'),
			array('id' =>94, 'education_qualification_id' => 15, 'name' => 'Other'),
			array('id' =>95, 'education_qualification_id' => 16, 'name' => 'Social Work'),
			array('id' =>96, 'education_qualification_id' => 17, 'name' => 'Other'),
			array('id' =>97, 'education_qualification_id' => 18, 'name' => 'Other'),
			array('id' =>98, 'education_qualification_id' => 19, 'name' => 'Other'),
			array('id' =>99, 'education_qualification_id' => 20, 'name' => 'Other'),
			array('id' =>100, 'education_qualification_id' => 21, 'name' => 'Social Work'),
			array('id' =>101, 'education_qualification_id' => 22, 'name' => 'Architecture'),
			array('id' =>102, 'education_qualification_id' => 22, 'name' => 'Hotel Management'),
			array('id' =>103, 'education_qualification_id' => 22, 'name' => 'Other Diploma'),
			array('id' =>104, 'education_qualification_id' => 22, 'name' => 'Computers'),
			array('id' =>105, 'education_qualification_id' => 22, 'name' => 'Cosmetics'),
			array('id' =>106, 'education_qualification_id' => 22, 'name' => 'Cosmetology'),
			array('id' =>107, 'education_qualification_id' => 22, 'name' => 'Fashion Design/Other Designing'),
			array('id' =>108, 'education_qualification_id' => 22, 'name' => 'Management'),
			array('id' =>109, 'education_qualification_id' => 22, 'name' => 'Visual Arts'),
			array('id' =>110, 'education_qualification_id' => 22, 'name' => 'Other Engineering'),
			array('id' =>111, 'education_qualification_id' => 22, 'name' => 'Vocational Courses'),
			array('id' =>112, 'education_qualification_id' => 22, 'name' => 'Any'),
			array('id' =>113, 'education_qualification_id' => 22, 'name' => 'Automobile engineering'),
			array('id' =>114, 'education_qualification_id' => 22, 'name' => 'Chemical engineering'),
			array('id' =>115, 'education_qualification_id' => 22, 'name' => 'Civil engineering'),
			array('id' =>116, 'education_qualification_id' => 22, 'name' => 'Electrical engineering'),
			array('id' =>117, 'education_qualification_id' => 22, 'name' => 'Electronics/Telecommunications'),
			array('id' =>118, 'education_qualification_id' => 22, 'name' => 'Export/Import'),
			array('id' =>119, 'education_qualification_id' => 22, 'name' => 'Graphic/Web Designing'),
			array('id' =>120, 'education_qualification_id' => 22, 'name' => 'Insurance'),
			array('id' =>121, 'education_qualification_id' => 22, 'name' => 'Mechanical engineering'),
			array('id' =>122, 'education_qualification_id' => 22, 'name' => 'Production/Industrial Engineering'),
			array('id' =>123, 'education_qualification_id' => 22, 'name' => 'Textile Engineering'),
			array('id' =>124, 'education_qualification_id' => 22, 'name' => 'Tourism'),
			array('id' =>125, 'education_qualification_id' => 23, 'name' => 'Other'),
			array('id' =>126, 'education_qualification_id' => 24, 'name' => 'Other'),
			array('id' =>127, 'education_qualification_id' => 25, 'name' => 'Other'),
			array('id' =>128, 'education_qualification_id' => 25, 'name' => 'Arts & Humanities'),
			array('id' =>129, 'education_qualification_id' => 25, 'name' => 'Communication'),
			array('id' =>130, 'education_qualification_id' => 25, 'name' => 'Economics'),
			array('id' =>131, 'education_qualification_id' => 25, 'name' => 'English'),
			array('id' =>132, 'education_qualification_id' => 25, 'name' => 'Film'),
			array('id' =>133, 'education_qualification_id' => 25, 'name' => 'Fine Arts'),
			array('id' =>134, 'education_qualification_id' => 25, 'name' => 'Hindi'),
			array('id' =>135, 'education_qualification_id' => 25, 'name' => 'History'),
			array('id' =>136, 'education_qualification_id' => 25, 'name' => 'Journalism'),
			array('id' =>137, 'education_qualification_id' => 25, 'name' => 'Literature'),
			array('id' =>138, 'education_qualification_id' => 25, 'name' => 'Mathematics'),
			array('id' =>139, 'education_qualification_id' => 25, 'name' => 'Philosophy'),
			array('id' =>140, 'education_qualification_id' => 25, 'name' => 'Political Science'),
			array('id' =>141, 'education_qualification_id' => 25, 'name' => 'PR/Advertising'),
			array('id' =>142, 'education_qualification_id' => 25, 'name' => 'Psychology'),
			array('id' =>143, 'education_qualification_id' => 25, 'name' => 'Sanskrit'),
			array('id' =>144, 'education_qualification_id' => 25, 'name' => 'Sociology'),
			array('id' =>145, 'education_qualification_id' => 25, 'name' => 'Statistics'),
			array('id' =>146, 'education_qualification_id' => 25, 'name' => 'Other Arts'),
			array('id' =>147, 'education_qualification_id' => 26, 'name' => 'Architecture'),
			array('id' =>148, 'education_qualification_id' => 27, 'name' => 'Other'),
			array('id' =>149, 'education_qualification_id' => 27, 'name' => 'Advertising/Mass Communication'),
			array('id' =>150, 'education_qualification_id' => 27, 'name' => 'Finance'),
			array('id' =>151, 'education_qualification_id' => 27, 'name' => 'General Management & Small Business'),
			array('id' =>152, 'education_qualification_id' => 27, 'name' => 'Healthcare Management'),
			array('id' =>153, 'education_qualification_id' => 27, 'name' => 'HR/Industrial Relations'),
			array('id' =>154, 'education_qualification_id' => 27, 'name' => 'Information Technology Management'),
			array('id' =>155, 'education_qualification_id' => 27, 'name' => 'International Management'),
			array('id' =>156, 'education_qualification_id' => 27, 'name' => 'Insurance & Risk Management'),
			array('id' =>157, 'education_qualification_id' => 27, 'name' => 'Marketing'),
			array('id' =>158, 'education_qualification_id' => 27, 'name' => 'Production & Operations Management'),
			array('id' =>159, 'education_qualification_id' => 27, 'name' => 'Retail Management'),
			array('id' =>160, 'education_qualification_id' => 27, 'name' => 'Strategy Management'),
			array('id' =>161, 'education_qualification_id' => 27, 'name' => 'Systems'),
			array('id' =>162, 'education_qualification_id' => 27, 'name' => 'Other Management'),
			array('id' =>163, 'education_qualification_id' => 28, 'name' => 'Medicine'),
			array('id' =>164, 'education_qualification_id' => 29, 'name' => 'Computers'),
			array('id' =>165, 'education_qualification_id' => 30, 'name' => 'Commerce'),
			array('id' =>166, 'education_qualification_id' => 31, 'name' => 'Biochemistry'),
			array('id' =>167, 'education_qualification_id' => 31, 'name' => 'Cardiology'),
			array('id' =>168, 'education_qualification_id' => 31, 'name' => 'Dermatology'),
			array('id' =>169, 'education_qualification_id' => 31, 'name' => 'Emergency Medicine'),
			array('id' =>170, 'education_qualification_id' => 31, 'name' => 'ENT'),
			array('id' =>171, 'education_qualification_id' => 31, 'name' => 'Gastroenterology'),
			array('id' =>172, 'education_qualification_id' => 31, 'name' => 'General Physician'),
			array('id' =>173, 'education_qualification_id' => 31, 'name' => 'Genetic Medicine'),
			array('id' =>174, 'education_qualification_id' => 31, 'name' => 'Gyneocology'),
			array('id' =>175, 'education_qualification_id' => 31, 'name' => 'Hepatology'),
			array('id' =>176, 'education_qualification_id' => 31, 'name' => 'Internal Medicine'),
			array('id' =>177, 'education_qualification_id' => 31, 'name' => 'Microbiology'),
			array('id' =>178, 'education_qualification_id' => 31, 'name' => 'Medicine'),
			array('id' =>179, 'education_qualification_id' => 31, 'name' => 'Nephrology'),
			array('id' =>180, 'education_qualification_id' => 31, 'name' => 'Neurology'),
			array('id' =>181, 'education_qualification_id' => 31, 'name' => 'Nuclear Medicine'),
			array('id' =>182, 'education_qualification_id' => 31, 'name' => 'Oncology'),
			array('id' =>183, 'education_qualification_id' => 31, 'name' => 'Opthalmology'),
			array('id' =>184, 'education_qualification_id' => 31, 'name' => 'Orthopaedic'),
			array('id' =>185, 'education_qualification_id' => 31, 'name' => 'Pathology'),
			array('id' =>186, 'education_qualification_id' => 31, 'name' => 'Pediatrics'),
			array('id' =>187, 'education_qualification_id' => 31, 'name' => 'Physiotherapy'),
			array('id' =>188, 'education_qualification_id' => 31, 'name' => 'Preventive and Social Medicine'),
			array('id' =>189, 'education_qualification_id' => 31, 'name' => 'Psychiatry'),
			array('id' =>190, 'education_qualification_id' => 31, 'name' => 'Radiology'),
			array('id' =>191, 'education_qualification_id' => 31, 'name' => 'Rehabilitation Medicine'),
			array('id' =>192, 'education_qualification_id' => 31, 'name' => 'Reproductive Medicine'),
			array('id' =>193, 'education_qualification_id' => 31, 'name' => 'Surgery'),
			array('id' =>194, 'education_qualification_id' => 31, 'name' => 'Urology'),
			array('id' =>195, 'education_qualification_id' => 31, 'name' => 'Other Doctor of Medicine (M.D/M.S) (Medicine)'),
			array('id' =>196, 'education_qualification_id' => 31, 'name' => 'Visual Communication'),
			array('id' =>197, 'education_qualification_id' => 32, 'name' => 'Education'),
			array('id' =>198, 'education_qualification_id' => 33, 'name' => 'Other'),
			array('id' =>199, 'education_qualification_id' => 33, 'name' => 'Agriculture'),
			array('id' =>200, 'education_qualification_id' => 33, 'name' => 'Applied Mechanics'),
			array('id' =>201, 'education_qualification_id' => 33, 'name' => 'Automobile'),
			array('id' =>202, 'education_qualification_id' => 33, 'name' => 'Aviation/Aeronautical'),
			array('id' =>203, 'education_qualification_id' => 33, 'name' => 'Bio-Chemistry/Bio-Technology'),
			array('id' =>204, 'education_qualification_id' => 33, 'name' => 'Biomedical'),
			array('id' =>205, 'education_qualification_id' => 33, 'name' => 'Ceramics'),
			array('id' =>206, 'education_qualification_id' => 33, 'name' => 'Chemical'),
			array('id' =>207, 'education_qualification_id' => 33, 'name' => 'Civil'),
			array('id' =>208, 'education_qualification_id' => 33, 'name' => 'Computers'),
			array('id' =>209, 'education_qualification_id' => 33, 'name' => 'Cosmetics'),
			array('id' =>210, 'education_qualification_id' => 33, 'name' => 'Cosmetology'),
			array('id' =>211, 'education_qualification_id' => 33, 'name' => 'Electrical'),
			array('id' =>212, 'education_qualification_id' => 33, 'name' => 'Electronics/Telecommunications'),
			array('id' =>213, 'education_qualification_id' => 33, 'name' => 'Energy'),
			array('id' =>214, 'education_qualification_id' => 33, 'name' => 'Environmental science'),
			array('id' =>215, 'education_qualification_id' => 33, 'name' => 'Instrumentation'),
			array('id' =>216, 'education_qualification_id' => 33, 'name' => 'Marine'),
			array('id' =>217, 'education_qualification_id' => 33, 'name' => 'Mathematics'),
			array('id' =>218, 'education_qualification_id' => 33, 'name' => 'Mechanical'),
			array('id' =>219, 'education_qualification_id' => 33, 'name' => 'Metallurgy'),
			array('id' =>220, 'education_qualification_id' => 33, 'name' => 'Mineral'),
			array('id' =>221, 'education_qualification_id' => 33, 'name' => 'Mining'),
			array('id' =>222, 'education_qualification_id' => 33, 'name' => 'Nuclear'),
			array('id' =>223, 'education_qualification_id' => 33, 'name' => 'Paint/Oil'),
			array('id' =>224, 'education_qualification_id' => 33, 'name' => 'Petroleum'),
			array('id' =>225, 'education_qualification_id' => 33, 'name' => 'Physics'),
			array('id' =>226, 'education_qualification_id' => 33, 'name' => 'Plastics'),
			array('id' =>227, 'education_qualification_id' => 33, 'name' => 'Production/Industrial'),
			array('id' =>228, 'education_qualification_id' => 33, 'name' => 'Solid State Technology'),
			array('id' =>229, 'education_qualification_id' => 33, 'name' => 'Textile'),
			array('id' =>230, 'education_qualification_id' => 33, 'name' => 'Other Engineering'),
			array('id' =>231, 'education_qualification_id' => 33, 'name' => 'Other'),
			array('id' =>232, 'education_qualification_id' => 33, 'name' => 'Agriculture'),
			array('id' =>233, 'education_qualification_id' => 33, 'name' => 'Anthropology'),
			array('id' =>234, 'education_qualification_id' => 33, 'name' => 'Applied Mechanics'),
			array('id' =>235, 'education_qualification_id' => 33, 'name' => 'Bio-Chemistry/Bio-Technology'),
			array('id' =>236, 'education_qualification_id' => 33, 'name' => 'Biology'),
			array('id' =>237, 'education_qualification_id' => 33, 'name' => 'Botany'),
			array('id' =>238, 'education_qualification_id' => 33, 'name' => 'Chemistry'),
			array('id' =>239, 'education_qualification_id' => 33, 'name' => 'Computers'),
			array('id' =>240, 'education_qualification_id' => 33, 'name' => 'Dairy Technology'),
			array('id' =>241, 'education_qualification_id' => 33, 'name' => 'Electronics'),
			array('id' =>242, 'education_qualification_id' => 33, 'name' => 'Environmental science'),
			array('id' =>243, 'education_qualification_id' => 33, 'name' => 'Food Technology'),
			array('id' =>244, 'education_qualification_id' => 33, 'name' => 'General'),
			array('id' =>245, 'education_qualification_id' => 33, 'name' => 'Geology'),
			array('id' =>246, 'education_qualification_id' => 33, 'name' => 'Home science'),
			array('id' =>247, 'education_qualification_id' => 33, 'name' => 'Mathematics'),
			array('id' =>248, 'education_qualification_id' => 33, 'name' => 'Microbiology'),
			array('id' =>249, 'education_qualification_id' => 33, 'name' => 'Nursing'),
			array('id' =>250, 'education_qualification_id' => 33, 'name' => 'Ocean'),
			array('id' =>251, 'education_qualification_id' => 33, 'name' => 'Physics'),
			array('id' =>252, 'education_qualification_id' => 33, 'name' => 'Statistics'),
			array('id' =>253, 'education_qualification_id' => 33, 'name' => 'Systems & Devices'),
			array('id' =>254, 'education_qualification_id' => 33, 'name' => 'Anesthesiology'),
			array('id' =>255, 'education_qualification_id' => 33, 'name' => 'Zoology'),
			array('id' =>256, 'education_qualification_id' => 33, 'name' => 'Other'),
			array('id' =>257, 'education_qualification_id' => 34, 'name' => 'Law'),
			array('id' =>258, 'education_qualification_id' => 35, 'name' => 'Pharmacy'),
			array('id' =>259, 'education_qualification_id' => 36, 'name' => 'Other'),
			array('id' =>260, 'education_qualification_id' => 36, 'name' => 'Advertising/Mass Communication'),
			array('id' =>261, 'education_qualification_id' => 36, 'name' => 'Agriculture'),
			array('id' =>262, 'education_qualification_id' => 36, 'name' => 'Architecture'),
			array('id' =>263, 'education_qualification_id' => 36, 'name' => 'Aviation/Aeronautical'),
			array('id' =>264, 'education_qualification_id' => 36, 'name' => 'Bio-Chemistry/Bio-Technology'),
			array('id' =>265, 'education_qualification_id' => 36, 'name' => 'Chemical'),
			array('id' =>266, 'education_qualification_id' => 36, 'name' => 'Chemistry'),
			array('id' =>267, 'education_qualification_id' => 36, 'name' => 'Civil'),
			array('id' =>268, 'education_qualification_id' => 36, 'name' => 'Commerce'),
			array('id' =>269, 'education_qualification_id' => 36, 'name' => 'Computers'),
			array('id' =>270, 'education_qualification_id' => 36, 'name' => 'Dairy Technology'),
			array('id' =>271, 'education_qualification_id' => 36, 'name' => 'Economics'),
			array('id' =>272, 'education_qualification_id' => 36, 'name' => 'Electrical'),
			array('id' =>273, 'education_qualification_id' => 36, 'name' => 'Electronics/Telecommunications'),
			array('id' =>274, 'education_qualification_id' => 36, 'name' => 'Fashion Design/Other Designing'),
			array('id' =>275, 'education_qualification_id' => 36, 'name' => 'Finance'),
			array('id' =>276, 'education_qualification_id' => 36, 'name' => 'Food Technology'),
			array('id' =>277, 'education_qualification_id' => 36, 'name' => 'Hotel Management'),
			array('id' =>278, 'education_qualification_id' => 36, 'name' => 'HR/Industrial Relations'),
			array('id' =>279, 'education_qualification_id' => 36, 'name' => 'Instrumentation'),
			array('id' =>280, 'education_qualification_id' => 36, 'name' => 'Journalism'),
			array('id' =>281, 'education_qualification_id' => 36, 'name' => 'Law'),
			array('id' =>282, 'education_qualification_id' => 36, 'name' => 'Literature'),
			array('id' =>283, 'education_qualification_id' => 36, 'name' => 'Marketing'),
			array('id' =>284, 'education_qualification_id' => 36, 'name' => 'Materials Science'),
			array('id' =>285, 'education_qualification_id' => 36, 'name' => 'Mechanical'),
			array('id' =>286, 'education_qualification_id' => 36, 'name' => 'Medicine'),
			array('id' =>287, 'education_qualification_id' => 36, 'name' => 'Metallurgy'),
			array('id' =>288, 'education_qualification_id' => 36, 'name' => 'Mining'),
			array('id' =>289, 'education_qualification_id' => 36, 'name' => 'Pharmacy'),
			array('id' =>290, 'education_qualification_id' => 36, 'name' => 'Physics'),
			array('id' =>291, 'education_qualification_id' => 36, 'name' => 'Production/Industrial'),
			array('id' =>292, 'education_qualification_id' => 36, 'name' => 'Psychology'),
			array('id' =>293, 'education_qualification_id' => 36, 'name' => 'Statistics'),
			array('id' =>294, 'education_qualification_id' => 36, 'name' => 'Systems'),
			array('id' =>295, 'education_qualification_id' => 36, 'name' => 'Visual Arts'),
			array('id' =>296, 'education_qualification_id' => 36, 'name' => 'Vocational Courses'),
			array('id' =>297, 'education_qualification_id' => 36, 'name' => 'Other Arts'),
			array('id' =>298, 'education_qualification_id' => 36, 'name' => 'Other Doctorate'),
			array('id' =>299, 'education_qualification_id' => 36, 'name' => 'Other Engineering'),
			array('id' =>300, 'education_qualification_id' => 36, 'name' => 'Other Management'),
			array('id' =>301, 'education_qualification_id' => 36, 'name' => 'Other Science'),
			array('id' =>302, 'education_qualification_id' => 37, 'name' => 'Social Work'),
			array('id' =>303, 'education_qualification_id' => 38, 'name' => 'Computers'),
			array('id' =>304, 'education_qualification_id' => 39, 'name' => 'Other'),
			array('id' =>305, 'education_qualification_id' => 39, 'name' => 'Advertising/Mass Communication'),
			array('id' =>306, 'education_qualification_id' => 39, 'name' => 'Finance'),
			array('id' =>307, 'education_qualification_id' => 39, 'name' => 'General Management & Small Business'),
			array('id' =>308, 'education_qualification_id' => 39, 'name' => 'HR/Industrial Relations'),
			array('id' =>309, 'education_qualification_id' => 39, 'name' => 'Information Technology Management'),
			array('id' =>310, 'education_qualification_id' => 39, 'name' => 'International Management'),
			array('id' =>311, 'education_qualification_id' => 39, 'name' => 'Marketing'),
			array('id' =>312, 'education_qualification_id' => 39, 'name' => 'Production & Operations Management'),
			array('id' =>313, 'education_qualification_id' => 39, 'name' => 'Strategy Management'),
			array('id' =>314, 'education_qualification_id' => 39, 'name' => 'Systems'),
			array('id' =>315, 'education_qualification_id' => 39, 'name' => 'Other Management'),
			array('id' =>316, 'education_qualification_id' => 40, 'name' => 'PGPX'),
			array('id' =>317, 'education_qualification_id' => 41, 'name' => 'Other'),
			array('id' =>318, 'education_qualification_id' => 41, 'name' => 'Advertising/Mass Communication'),
			array('id' =>319, 'education_qualification_id' => 41, 'name' => 'Agriculture'),
			array('id' =>320, 'education_qualification_id' => 41, 'name' => 'Architecture'),
			array('id' =>321, 'education_qualification_id' => 41, 'name' => 'Aviation/Aeronautical'),
			array('id' =>322, 'education_qualification_id' => 41, 'name' => 'Bio-Chemistry/Bio-Technology'),
			array('id' =>323, 'education_qualification_id' => 41, 'name' => 'Chemical'),
			array('id' =>324, 'education_qualification_id' => 41, 'name' => 'Chemistry'),
			array('id' =>325, 'education_qualification_id' => 41, 'name' => 'Civil'),
			array('id' =>326, 'education_qualification_id' => 41, 'name' => 'Commerce'),
			array('id' =>327, 'education_qualification_id' => 41, 'name' => 'Computers'),
			array('id' =>328, 'education_qualification_id' => 41, 'name' => 'Dairy Technology'),
			array('id' =>329, 'education_qualification_id' => 41, 'name' => 'Economics'),
			array('id' =>330, 'education_qualification_id' => 41, 'name' => 'Electrical'),
			array('id' =>331, 'education_qualification_id' => 41, 'name' => 'Electronics/Telecommunications'),
			array('id' =>332, 'education_qualification_id' => 41, 'name' => 'Fashion Design/Other Designing'),
			array('id' =>333, 'education_qualification_id' => 41, 'name' => 'Finance'),
			array('id' =>334, 'education_qualification_id' => 41, 'name' => 'Food Technology'),
			array('id' =>335, 'education_qualification_id' => 41, 'name' => 'Hotel Management'),
			array('id' =>336, 'education_qualification_id' => 41, 'name' => 'HR/Industrial Relations'),
			array('id' =>337, 'education_qualification_id' => 41, 'name' => 'Instrumentation'),
			array('id' =>338, 'education_qualification_id' => 41, 'name' => 'Journalism'),
			array('id' =>339, 'education_qualification_id' => 41, 'name' => 'Law'),
			array('id' =>340, 'education_qualification_id' => 41, 'name' => 'Literature'),
			array('id' =>341, 'education_qualification_id' => 41, 'name' => 'Marketing'),
			array('id' =>342, 'education_qualification_id' => 41, 'name' => 'Materials Science'),
			array('id' =>343, 'education_qualification_id' => 41, 'name' => 'Mechanical'),
			array('id' =>344, 'education_qualification_id' => 41, 'name' => 'Medicine'),
			array('id' =>345, 'education_qualification_id' => 41, 'name' => 'Metallurgy'),
			array('id' =>346, 'education_qualification_id' => 41, 'name' => 'Mining'),
			array('id' =>347, 'education_qualification_id' => 41, 'name' => 'Pharmacy'),
			array('id' =>348, 'education_qualification_id' => 41, 'name' => 'Physics'),
			array('id' =>349, 'education_qualification_id' => 41, 'name' => 'Production/Industrial'),
			array('id' =>350, 'education_qualification_id' => 41, 'name' => 'Psychology'),
			array('id' =>351, 'education_qualification_id' => 41, 'name' => 'Statistics'),
			array('id' =>352, 'education_qualification_id' => 41, 'name' => 'Systems'),
			array('id' =>353, 'education_qualification_id' => 41, 'name' => 'Visual Arts'),
			array('id' =>354, 'education_qualification_id' => 41, 'name' => 'Vocational Courses'),
			array('id' =>355, 'education_qualification_id' => 41, 'name' => 'Other Arts'),
			array('id' =>356, 'education_qualification_id' => 41, 'name' => 'Other Doctorate'),
			array('id' =>357, 'education_qualification_id' => 41, 'name' => 'Other Engineering'),
			array('id' =>358, 'education_qualification_id' => 41, 'name' => 'Other Management'),
			array('id' =>359, 'education_qualification_id' => 41, 'name' => 'Other Science'),
			array('id' =>360, 'education_qualification_id' => 42, 'name' => 'Other'),

        );

        DB::table("education_specialization")->insert($data);
    }
}
