<?php

use Illuminate\Database\Seeder;

class FunctionalRolesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement("SET FOREIGN_KEY_CHECKS=0;");
        DB::table("functional_roles")->truncate();

        $data = array( 

        	array('id' =>1, 'name' => 'Admin/Secretary'),
			array('id' =>2, 'name' => 'Fresher'),
			array('id' =>3, 'name' => 'Travel/Immigration Coordinator'),
			array('id' =>4, 'name' => 'Administration Executive'),
			array('id' =>5, 'name' => 'Computer Operator/Data Entry'),
			array('id' =>6, 'name' => 'Typist'),
			array('id' =>7, 'name' => 'Despatch Incharge'),
			array('id' =>8, 'name' => 'Receptionist/Front Desk'),
			array('id' =>9, 'name' => 'Executive Secretary/Personal Assistant'),
			array('id' =>10, 'name' => 'Facilities Manager'),
			array('id' =>11, 'name' => 'Administration Manager'),
			array('id' =>12, 'name' => 'VP/GM - Administration'),
			array('id' =>13, 'name' => 'Customer Service/Call Centre/BPO'),
			array('id' =>14, 'name' => 'Trainee/Management Trainee'),
			array('id' =>15, 'name' => 'Technical Support Executive (Voice)'),
			array('id' =>16, 'name' => 'Technical Support Representative (Non- Voice)'),
			array('id' =>17, 'name' => 'Customer Service Executive (Voice)'),
			array('id' =>18, 'name' => 'Customer Service Executive (Non-Voice)'),
			array('id' =>19, 'name' => 'Data Processing Executive'),
			array('id' =>20, 'name' => 'Telesales Executive'),
			array('id' =>21, 'name' => 'Telemarketing Executive'),
			array('id' =>22, 'name' => 'Manager - Data Processing'),
			array('id' =>23, 'name' => 'Team Leader'),
			array('id' =>24, 'name' => 'Medical Transcriptionist'),
			array('id' =>25, 'name' => 'Transactions Processing Executive'),
			array('id' =>26, 'name' => 'AR Caller/AR Analyst'),
			array('id' =>27, 'name' => 'Account Services Executive'),
			array('id' =>28, 'name' => 'Operations Manager'),
			array('id' =>29, 'name' => 'Manager - Service Delivery'),
			array('id' =>30, 'name' => 'Technical Trainer'),
			array('id' =>31, 'name' => 'Quality Assurance - Manager'),
			array('id' =>32, 'name' => 'VP/GM - Quality'),
			array('id' =>33, 'name' => 'Shift Supervisor'),
			array('id' =>34, 'name' => 'Training Manager'),
			array('id' =>35, 'name' => 'Manager - Migrations/Transitions'),
			array('id' =>36, 'name' => 'Process/Work Flow Analyst'),
			array('id' =>37, 'name' => 'Quality Assurance Executive'),
			array('id' =>38, 'name' => 'Voice & Accent Trainer'),
			array('id' =>39, 'name' => 'Process Trainer '),
			array('id' =>40, 'name' => 'Soft Skills Trainer'),
			array('id' =>41, 'name' => 'VP/Head - Customer Service'),
			array('id' =>42, 'name' => 'VP - Operations/COO'),
			array('id' =>43, 'name' => 'SBU Head/Profit Centre Head'),
			array('id' =>44, 'name' => 'CEO/MD/Country Manager'),
			array('id' =>45, 'name' => 'Director on Board'),
			array('id' =>46, 'name' => 'External Consultant'),
			array('id' =>47, 'name' => 'Other Customer Service/Call Center'),
			array('id' =>48, 'name' => 'Finance & Accounts'),
			array('id' =>49, 'name' => 'Graduate Trainee/Management Trainee'),
			array('id' =>50, 'name' => 'Book Keeper/Accounts Assistant'),
			array('id' =>51, 'name' => 'Accountant'),
			array('id' =>52, 'name' => 'Accounts Manager'),
			array('id' =>53, 'name' => 'Cost Accountant/ICWA'),
			array('id' =>54, 'name' => 'Chartered Accountant (CPA)'),
			array('id' =>55, 'name' => 'Accounts Head/GM - Accounts'),
			array('id' =>56, 'name' => 'Finance Assistant'),
			array('id' =>57, 'name' => 'Financial Controller'),
			array('id' =>58, 'name' => 'Manager - Financial Planning/Budgeting'),
			array('id' =>59, 'name' => 'Finance Manager'),
			array('id' =>60, 'name' => 'Financial/Business Analyst'),
			array('id' =>61, 'name' => 'Head/GM - Finance'),
			array('id' =>62, 'name' => 'Internal Auditor'),
			array('id' =>63, 'name' => 'External Auditor'),
			array('id' =>64, 'name' => 'Commercial Executive/Manager'),
			array('id' =>65, 'name' => 'Credit Control & Collections'),
			array('id' =>66, 'name' => 'Graphic Designer/Animator'),
			array('id' =>67, 'name' => 'Medical Practitioner'),
			array('id' =>68, 'name' => 'ERP/CRM - Technical Consultant'),
			array('id' =>69, 'name' => 'Treasury Manager'),
			array('id' =>70, 'name' => 'Company Secretary'),
			array('id' =>71, 'name' => 'Taxation - Manager'),
			array('id' =>72, 'name' => 'Shares Services Executive'),
			array('id' =>73, 'name' => 'Foreign Exchange Officer '),
			array('id' =>74, 'name' => 'Payroll/Compensation Executive'),
			array('id' =>75, 'name' => 'Payroll/Compensation - Manager/Head'),
			array('id' =>76, 'name' => 'GM/Head/VP - Corporate Planning/Strategy'),
			array('id' =>77, 'name' => 'VP - Finance/CFO'),
			array('id' =>78, 'name' => 'Other Finance & Accounts'),
			array('id' =>79, 'name' => 'Human Resources'),
			array('id' =>80, 'name' => 'HR Executive/Recruiter'),
			array('id' =>81, 'name' => 'HR Manager'),
			array('id' =>82, 'name' => 'HR Business Partner'),
			array('id' =>83, 'name' => 'Training & Development Executive'),
			array('id' =>84, 'name' => 'Payroll/Compensation - Head/Mgr'),
			array('id' =>85, 'name' => 'Recruitment - Head/Mgr'),
			array('id' =>86, 'name' => 'Training & Development - Head/Mgr'),
			array('id' =>87, 'name' => 'Appraisals - Head/Mgr'),
			array('id' =>88, 'name' => 'Industrial Relations/Personnel Manager'),
			array('id' =>89, 'name' => 'VP/GM - HR'),
			array('id' =>90, 'name' => 'Other Human Resource'),
			array('id' =>91, 'name' => 'IT'),
			array('id' =>92, 'name' => 'Trainee'),
			array('id' =>93, 'name' => 'Software Engineer/Programmer'),
			array('id' =>94, 'name' => 'Systems Engineer'),
			array('id' =>95, 'name' => 'Team Leader/Technical Leader'),
			array('id' =>96, 'name' => 'System Analyst/Tech Architect'),
			array('id' =>97, 'name' => 'Business Analyst'),
			array('id' =>98, 'name' => 'Project Leader/Project Manager'),
			array('id' =>99, 'name' => 'Database Administrator (DBA)'),
			array('id' =>100, 'name' => 'Database Architect/Designer'),
			array('id' =>101, 'name' => 'Delivery Manager'),
			array('id' =>102, 'name' => 'Program Manager'),
			array('id' =>103, 'name' => 'Datawarehousing Consultants'),
			array('id' =>104, 'name' => 'System Administrator'),
			array('id' =>105, 'name' => 'H/W Installation/Maintenance Engg'),
			array('id' =>106, 'name' => 'Network Administrator'),
			array('id' =>107, 'name' => 'Network Designer'),
			array('id' =>108, 'name' => 'Security Analyst'),
			array('id' =>109, 'name' => 'System Security - Engineer'),
			array('id' =>110, 'name' => 'Technical Support Engineer'),
			array('id' =>111, 'name' => 'Software Test Engineer'),
			array('id' =>112, 'name' => 'System Integrator'),
			array('id' =>113, 'name' => 'ERP/CRM - Functional Consultant'),
			array('id' =>114, 'name' => 'ERP/CRM - Support Engineer'),
			array('id' =>115, 'name' => 'S/W Installation/Maintenance Engg'),
			array('id' =>116, 'name' => 'Product Manager'),
			array('id' =>117, 'name' => 'Configuration Mgr/Release Manager'),
			array('id' =>118, 'name' => 'Trainer/Faculty'),
			array('id' =>119, 'name' => 'Technical Writer'),
			array('id' =>120, 'name' => 'Web Master/Web Site Manager'),
			array('id' =>121, 'name' => 'SEO Expert'),
			array('id' =>122, 'name' => 'Hardware Design Engineer'),
			array('id' =>123, 'name' => 'Hardware Design Technical Leader'),
			array('id' =>124, 'name' => 'Instructional Designer'),
			array('id' =>125, 'name' => 'EDP Analyst'),
			array('id' =>126, 'name' => 'IT/Networking (EDP) - Manager'),
			array('id' =>127, 'name' => 'Information Systems (MIS) - Manager'),
			array('id' =>128, 'name' => 'MIS Executive'),
			array('id' =>129, 'name' => 'VP/Head - Technology (IT)'),
			array('id' =>130, 'name' => 'Chief Technology Officer (CTO)'),
			array('id' =>131, 'name' => 'Chief Information Officer (CIO)'),
			array('id' =>132, 'name' => 'Other Software/Hardware/EDP'),
			array('id' =>133, 'name' => 'Project Co-ordinator'),
			array('id' =>134, 'name' => 'Legal'),
			array('id' =>135, 'name' => 'Lawyer/Attorney'),
			array('id' =>136, 'name' => 'Legal Advisor'),
			array('id' =>137, 'name' => 'Legal Assistant/Apprentcie'),
			array('id' =>138, 'name' => 'Legal Consultant/Solicitor'),
			array('id' =>139, 'name' => 'Law Officer'),
			array('id' =>140, 'name' => 'Patent'),
			array('id' =>141, 'name' => 'Private Practitioner/Lawyer'),
			array('id' =>142, 'name' => 'Proof Reader (Law)'),
			array('id' =>143, 'name' => 'Legal Editor'),
			array('id' =>144, 'name' => 'Legal Services - Manager'),
			array('id' =>145, 'name' => 'Legal Head'),
			array('id' =>146, 'name' => 'Other Legal/Law'),
			array('id' =>147, 'name' => 'Marketing & Communications'),
			array('id' =>148, 'name' => 'Telesales/Telemarketing Executive'),
			array('id' =>149, 'name' => 'Corp Communications - Manager/Executive'),
			array('id' =>150, 'name' => 'Head - Corp Communications'),
			array('id' =>151, 'name' => 'Advertising - Executive'),
			array('id' =>152, 'name' => 'Advertising - Manager'),
			array('id' =>153, 'name' => 'Public Relations - Executive'),
			array('id' =>154, 'name' => 'Public Relations - Manager'),
			array('id' =>155, 'name' => 'Events/Promotions Manager'),
			array('id' =>156, 'name' => 'Manager/Head - Internet Marketing'),
			array('id' =>157, 'name' => 'Direct Marketing - Executive'),
			array('id' =>158, 'name' => 'Direct Marketing - Manager'),
			array('id' =>159, 'name' => 'Market Research - Executive'),
			array('id' =>160, 'name' => 'Market Research - Manager'),
			array('id' =>161, 'name' => 'Marketing Executive'),
			array('id' =>162, 'name' => 'Marketing Manager'),
			array('id' =>163, 'name' => 'Alliances Manager'),
			array('id' =>164, 'name' => 'Business Analyst/Consultant'),
			array('id' =>165, 'name' => 'Brand Manager'),
			array('id' =>166, 'name' => 'Product Executive'),
			array('id' =>167, 'name' => 'Product Manager/Product Head'),
			array('id' =>168, 'name' => 'Marcom Executive'),
			array('id' =>169, 'name' => 'Marcom - Manager/Head'),
			array('id' =>170, 'name' => 'Executive - Internet Marketing'),
			array('id' =>171, 'name' => 'Social Media Executive'),
			array('id' =>172, 'name' => 'Head - Direct Marketing'),
			array('id' =>173, 'name' => 'Head - Public Relations'),
			array('id' =>174, 'name' => 'Head - Advertising'),
			array('id' =>175, 'name' => 'VP/GM/Head - Marketing'),
			array('id' =>176, 'name' => 'Other Marketing'),
			array('id' =>177, 'name' => 'Purchase/Logistics/Supply Chain'),
			array('id' =>178, 'name' => 'Freight Forwarding'),
			array('id' =>179, 'name' => 'Transit Centre (Rail) - Executive'),
			array('id' =>180, 'name' => 'Distribution - Head'),
			array('id' =>181, 'name' => 'Transportation/Shipping Supervisor'),
			array('id' =>182, 'name' => 'Logistics Co-ordinator'),
			array('id' =>183, 'name' => 'Logistics - Head/Mgr'),
			array('id' =>184, 'name' => 'Purchase Officer/Co-ordinator/Executive'),
			array('id' =>185, 'name' => 'Purchase Manager'),
			array('id' =>186, 'name' => 'Purchase - Head'),
			array('id' =>187, 'name' => 'Vendor Development Manager'),
			array('id' =>188, 'name' => 'Inventory Control Manager/Materials Manager'),
			array('id' =>189, 'name' => 'Country Network Coordinator'),
			array('id' =>190, 'name' => 'POD Management'),
			array('id' =>191, 'name' => 'Traffic Clerk'),
			array('id' =>192, 'name' => 'Fleet Supervisor'),
			array('id' =>193, 'name' => 'Supply Chain - Head'),
			array('id' =>194, 'name' => 'Store Keeper/Warehouse Assistant'),
			array('id' =>195, 'name' => 'Commercial - Manager'),
			array('id' =>196, 'name' => 'Materials - Head/GM'),
			array('id' =>197, 'name' => 'VP/GM - Commercial'),
			array('id' =>198, 'name' => 'Other Purchase/Supply Chain'),
			array('id' =>199, 'name' => 'Sales/Business Development'),
			array('id' =>200, 'name' => 'Sales Trainee/Management Trainee'),
			array('id' =>201, 'name' => 'Sales Exec/Sales Representative'),
			array('id' =>202, 'name' => 'Medical Representative'),
			array('id' =>203, 'name' => 'Channel Sales Manager'),
			array('id' =>204, 'name' => 'Relationship Mgr/Account Servicing'),
			array('id' =>205, 'name' => 'Key Accounts Manager'),
			array('id' =>206, 'name' => 'Institutional sales'),
			array('id' =>207, 'name' => 'Business Development Manager'),
			array('id' =>208, 'name' => 'Business Development Executive'),
			array('id' =>209, 'name' => 'Regional Sales Manager'),
			array('id' =>210, 'name' => 'Area/Territory Sales Manager'),
			array('id' =>211, 'name' => 'Sales Promotion Manager'),
			array('id' =>212, 'name' => 'International Business Dev Mgr'),
			array('id' =>213, 'name' => 'Branch Manager'),
			array('id' =>214, 'name' => 'Merchandiser'),
			array('id' =>215, 'name' => 'Direct Sales Agent/Commission Agent'),
			array('id' =>216, 'name' => 'Sales Trainer'),
			array('id' =>217, 'name' => 'Presales Consultant'),
			array('id' =>218, 'name' => 'Sales Engineer'),
			array('id' =>219, 'name' => 'Sales Coordinator'),
			array('id' =>220, 'name' => 'National Sales Manager'),
			array('id' =>221, 'name' => 'VP/GM/Head - Sales'),
			array('id' =>222, 'name' => 'Other Sales'),
			array('id' =>223, 'name' => 'Corporate Sales'),
			array('id' =>224, 'name' => 'Advertising/Entertainment/Media'),
			array('id' =>225, 'name' => 'Media Buying'),
			array('id' =>226, 'name' => 'Media Planning'),
			array('id' =>227, 'name' => 'Market Research'),
			array('id' =>228, 'name' => 'Editor/Managing Editor'),
			array('id' =>229, 'name' => 'Account Servicing'),
			array('id' =>230, 'name' => 'Correspondent/Reporter'),
			array('id' =>231, 'name' => 'Producer/Production Manager'),
			array('id' =>232, 'name' => 'TV Anchor'),
			array('id' =>233, 'name' => 'Art Director'),
			array('id' =>234, 'name' => 'Translator'),
			array('id' =>235, 'name' => 'AV Executive/Editor'),
			array('id' =>236, 'name' => 'Musician/Music Director'),
			array('id' =>237, 'name' => 'Event Management'),
			array('id' =>238, 'name' => 'Content Writer'),
			array('id' =>239, 'name' => 'Copy Writer'),
			array('id' =>240, 'name' => 'Photographer'),
			array('id' =>241, 'name' => 'Cameraman'),
			array('id' =>242, 'name' => 'Printing Technologist/Manager'),
			array('id' =>243, 'name' => 'Studio Operations Manager'),
			array('id' =>244, 'name' => 'Account Planning'),
			array('id' =>245, 'name' => 'Choreographer'),
			array('id' =>246, 'name' => 'Head - Lighting'),
			array('id' =>247, 'name' => 'Sound Mixer/Engineer'),
			array('id' =>248, 'name' => 'VJ/RJ/DJ'),
			array('id' =>249, 'name' => 'VP - Media Planning & Buying'),
			array('id' =>250, 'name' => 'Creative Director'),
			array('id' =>251, 'name' => 'VP - Client Servicing'),
			array('id' =>252, 'name' => 'Chief/Deputy Chief of Bureau'),
			array('id' =>253, 'name' => 'Proof Reader'),
			array('id' =>254, 'name' => 'Other Media/Journalism'),
			array('id' =>255, 'name' => 'Banking, Insurance & Financial Services'),
			array('id' =>256, 'name' => 'Relationship manager'),
			array('id' =>257, 'name' => 'Actuary Manager - Life'),
			array('id' =>258, 'name' => 'Actuary Manager - General'),
			array('id' =>259, 'name' => 'Phone Banking Officer'),
			array('id' =>260, 'name' => 'Consumer Banking Asset Operations'),
			array('id' =>261, 'name' => 'Audit'),
			array('id' =>262, 'name' => 'Banc Assurance - General'),
			array('id' =>263, 'name' => 'M&A Advisor'),
			array('id' =>264, 'name' => 'Cash Officer/Manager'),
			array('id' =>265, 'name' => 'Claims Management'),
			array('id' =>266, 'name' => 'Clearing Officer/Head'),
			array('id' =>267, 'name' => 'Collections'),
			array('id' =>268, 'name' => 'Compliance & Control'),
			array('id' =>269, 'name' => 'Ratings Analyst'),
			array('id' =>270, 'name' => 'Derivatives Analyst'),
			array('id' =>271, 'name' => 'Investment Banking'),
			array('id' =>272, 'name' => 'Trade Finance/Cash Mgmt Services - Head/Mgr'),
			array('id' =>273, 'name' => 'Product Manager - Mutual Funds'),
			array('id' =>274, 'name' => 'Product Manager - General'),
			array('id' =>275, 'name' => 'Product Manager - Cards'),
			array('id' =>276, 'name' => 'Product Manager - Life'),
			array('id' =>277, 'name' => 'Product Manager - Auto/Home/Personal Loan'),
			array('id' =>278, 'name' => 'Credit Research Analyst'),
			array('id' =>279, 'name' => 'Hedge Fund Analyst/Trader'),
			array('id' =>280, 'name' => 'Commodity Dealer'),
			array('id' =>281, 'name' => 'Equity Dealer'),
			array('id' =>282, 'name' => 'Agency Manager'),
			array('id' =>283, 'name' => 'Private Banker'),
			array('id' =>284, 'name' => 'Depository Participant'),
			array('id' =>285, 'name' => 'Project Finance - Head/Mgr'),
			array('id' =>286, 'name' => 'Consumer Branch Banking Operations'),
			array('id' =>287, 'name' => 'Consumer Banking Branch Head'),
			array('id' =>288, 'name' => 'Consumer Banking Region Head'),
			array('id' =>289, 'name' => 'Corporate Banking Credit Analyst'),
			array('id' =>290, 'name' => 'Credit Head - Consumer Banking'),
			array('id' =>291, 'name' => 'Corporate Banking Credit Control Manager'),
			array('id' =>292, 'name' => 'Corporate Banking Branch Head'),
			array('id' =>293, 'name' => 'Corporate Banking Region Head'),
			array('id' =>294, 'name' => 'Corporate Banking Customer Support Manager'),
			array('id' =>295, 'name' => 'Corporate Banking Credit Head'),
			array('id' =>296, 'name' => 'Cash Management Operations'),
			array('id' =>297, 'name' => 'GM - Treasury'),
			array('id' =>298, 'name' => 'Treasury Marketing Fixed Income'),
			array('id' =>299, 'name' => 'GM - Risks'),
			array('id' =>300, 'name' => 'Insurance Advisor - General'),
			array('id' =>301, 'name' => 'Insurance Operations Officer'),
			array('id' =>302, 'name' => 'Insurance Operations Manager'),
			array('id' =>303, 'name' => 'Insurance Advisor - Life'),
			array('id' =>304, 'name' => 'Investment Advisor'),
			array('id' =>305, 'name' => 'Portfolio Manager'),
			array('id' =>306, 'name' => 'Securities Analyst/Stock Broker'),
			array('id' =>307, 'name' => 'Economist'),
			array('id' =>308, 'name' => 'Trading Advisor'),
			array('id' =>309, 'name' => 'Underwriter - Life'),
			array('id' =>310, 'name' => 'Consumer Banking Head'),
			array('id' =>311, 'name' => 'Corporate Banking Head'),
			array('id' =>312, 'name' => 'Other Banking'),
			array('id' =>313, 'name' => 'Legal Officer - Life'),
			array('id' =>314, 'name' => 'Legal Officer - General'),
			array('id' =>315, 'name' => 'Legal Manager - General'),
			array('id' =>316, 'name' => 'Legal Manager - Life'),
			array('id' =>317, 'name' => 'Underwriter - General'),
			array('id' =>318, 'name' => 'Head - Underwriting - General'),
			array('id' =>319, 'name' => 'Construction'),
			array('id' =>320, 'name' => 'Architect'),
			array('id' =>321, 'name' => 'Civil Engineer'),
			array('id' =>322, 'name' => 'Mechanical Engineer'),
			array('id' =>323, 'name' => 'Design Engineer'),
			array('id' =>324, 'name' => 'HVAC engineering'),
			array('id' =>325, 'name' => 'Electrical Engineer'),
			array('id' =>326, 'name' => 'Desalinational engineering'),
			array('id' =>327, 'name' => 'Duct engineers'),
			array('id' =>328, 'name' => 'Maintenance Engineer'),
			array('id' =>329, 'name' => 'Contracting'),
			array('id' =>330, 'name' => 'Detailer'),
			array('id' =>331, 'name' => 'Civil Foreman'),
			array('id' =>332, 'name' => 'Draftsman'),
			array('id' =>333, 'name' => 'Quantity surveyor'),
			array('id' =>334, 'name' => 'Process Reporting manager'),
			array('id' =>335, 'name' => 'Project Manager'),
			array('id' =>336, 'name' => 'Proposals & Estimation'),
			array('id' =>337, 'name' => 'Surveyor'),
			array('id' =>338, 'name' => 'Document Controller'),
			array('id' =>339, 'name' => 'Marine engineering'),
			array('id' =>340, 'name' => 'MEP - Buyers'),
			array('id' =>341, 'name' => 'MEP - Surveyors'),
			array('id' =>342, 'name' => 'Plumbing engineer'),
			array('id' =>343, 'name' => 'Power & Telecom engineering'),
			array('id' =>344, 'name' => 'Safety Officer'),
			array('id' =>345, 'name' => 'Planning Engineer'),
			array('id' =>346, 'name' => 'Site engineer'),
			array('id' =>347, 'name' => 'Scaffolding Sales Professionals'),
			array('id' =>348, 'name' => 'Structural Designing'),
			array('id' =>349, 'name' => 'Water Treatment'),
			array('id' =>350, 'name' => 'Construction Suptd/Inspector'),
			array('id' =>351, 'name' => 'Director - Constructions'),
			array('id' =>352, 'name' => 'Director - Architecture'),
			array('id' =>353, 'name' => 'Director - Projects'),
			array('id' =>354, 'name' => 'VP/GM - Constructions'),
			array('id' =>355, 'name' => 'VP/GM - Architecture'),
			array('id' =>356, 'name' => 'VP/GM - Projects'),
			array('id' =>357, 'name' => 'Other Construction'),
			array('id' =>358, 'name' => 'Education/Teaching'),
			array('id' =>359, 'name' => 'Librarian'),
			array('id' =>360, 'name' => 'Kindergarten/Pre-primary Teacher'),
			array('id' =>361, 'name' => 'Language Teacher'),
			array('id' =>362, 'name' => 'Mathematics Teacher'),
			array('id' =>363, 'name' => 'Science Teacher'),
			array('id' =>364, 'name' => 'Social Sciences Teacher'),
			array('id' =>365, 'name' => 'Music/Dance Teacher'),
			array('id' =>366, 'name' => 'IT Instructor'),
			array('id' =>367, 'name' => 'Laboratory Assistant'),
			array('id' =>368, 'name' => 'Computer Teacher'),
			array('id' =>369, 'name' => 'Trainer'),
			array('id' =>370, 'name' => 'School Coordinator'),
			array('id' =>371, 'name' => 'Principal/Head of School'),
			array('id' =>372, 'name' => 'Lecturer/Professor'),
			array('id' =>373, 'name' => 'CEO/MD'),
			array('id' =>374, 'name' => 'Others'),
			array('id' =>375, 'name' => 'Export/Import'),
			array('id' =>376, 'name' => 'Trading'),
			array('id' =>377, 'name' => 'Documentation/Shipment Management'),
			array('id' =>378, 'name' => 'Liaison'),
			array('id' =>379, 'name' => 'Other Export/Import'),
			array('id' =>380, 'name' => 'Health Care'),
			array('id' =>381, 'name' => 'Trainee/Intern'),
			array('id' =>382, 'name' => 'Doctor'),
			array('id' =>383, 'name' => 'Physician'),
			array('id' =>384, 'name' => 'Dietician'),
			array('id' =>385, 'name' => 'Consultant'),
			array('id' =>386, 'name' => 'Pathologist'),
			array('id' =>387, 'name' => 'Surgeon'),
			array('id' =>388, 'name' => 'Orthopaedist'),
			array('id' =>389, 'name' => 'Psychiatrist'),
			array('id' =>390, 'name' => 'Specialist - Medicine'),
			array('id' =>391, 'name' => 'Nephrologist'),
			array('id' =>392, 'name' => 'Physiotherapist'),
			array('id' =>393, 'name' => 'Psycologist'),
			array('id' =>394, 'name' => 'Occupational Therapist'),
			array('id' =>395, 'name' => 'Microbiologist'),
			array('id' =>396, 'name' => 'Chemist'),
			array('id' =>397, 'name' => 'Optometrist'),
			array('id' =>398, 'name' => 'Radiologist'),
			array('id' =>399, 'name' => 'Pharmacist'),
			array('id' =>400, 'name' => 'Perfusionist'),
			array('id' =>401, 'name' => 'Anaesthetist'),
			array('id' =>402, 'name' => 'Ayurvedic Doctor'),
			array('id' =>403, 'name' => 'Opthalmologist'),
			array('id' =>404, 'name' => 'Nurse'),
			array('id' =>405, 'name' => 'Hearing Aid Technician'),
			array('id' =>406, 'name' => 'Lab Technician'),
			array('id' =>407, 'name' => 'Bio-chemist'),
			array('id' =>408, 'name' => 'Radiographer'),
			array('id' =>409, 'name' => 'ECG/CGA Technician'),
			array('id' =>410, 'name' => 'Operation Theater Technician'),
			array('id' =>411, 'name' => 'Medical Officer'),
			array('id' =>412, 'name' => 'Front Office'),
			array('id' =>413, 'name' => 'Patient Service Associate'),
			array('id' =>414, 'name' => 'Medical Coder'),
			array('id' =>415, 'name' => 'House Keeping'),
			array('id' =>416, 'name' => 'Cardiologist'),
			array('id' =>417, 'name' => 'Dentist'),
			array('id' =>418, 'name' => 'Dermatologist'),
			array('id' =>419, 'name' => 'ENT Specialist'),
			array('id' =>420, 'name' => 'Gastronomist/Gastrologist'),
			array('id' =>421, 'name' => 'Gyanecologist'),
			array('id' =>422, 'name' => 'Medical Lab Supervisor'),
			array('id' =>423, 'name' => 'Medical Superintendent/Dean/director'),
			array('id' =>424, 'name' => 'Neurologist'),
			array('id' =>425, 'name' => 'Hepatologist'),
			array('id' =>426, 'name' => 'Oncologist'),
			array('id' =>427, 'name' => 'Pediatrician'),
			array('id' =>428, 'name' => 'Pulmonologist'),
			array('id' =>429, 'name' => 'Speech Language Pathologist/Therapist'),
			array('id' =>430, 'name' => 'Other Health Care/Hospitals'),
			array('id' =>431, 'name' => 'Hotels/restaurants'),
			array('id' =>432, 'name' => 'Banquet Manager'),
			array('id' =>433, 'name' => 'Bartender'),
			array('id' =>434, 'name' => 'Butler'),
			array('id' =>435, 'name' => 'Chief Chef'),
			array('id' =>436, 'name' => 'F&B Manager'),
			array('id' =>437, 'name' => 'Lobby/Duty Manager'),
			array('id' =>438, 'name' => 'Front Office Executive'),
			array('id' =>439, 'name' => 'Front Office Manager'),
			array('id' =>440, 'name' => 'Guest Relations Manager'),
			array('id' =>441, 'name' => 'Banquet Sales'),
			array('id' =>442, 'name' => 'Health Club Manager'),
			array('id' =>443, 'name' => 'Hostess/Host'),
			array('id' =>444, 'name' => 'Guest Relations Executive'),
			array('id' =>445, 'name' => 'House Keeping - Head/Manager'),
			array('id' =>446, 'name' => 'Maintenance Technician'),
			array('id' =>447, 'name' => 'Reservation Manager'),
			array('id' =>448, 'name' => 'Steward/Waiter'),
			array('id' =>449, 'name' => 'Restaurant Manager'),
			array('id' =>450, 'name' => 'Club Floor Manager'),
			array('id' =>451, 'name' => 'Business Center Manager'),
			array('id' =>452, 'name' => 'House Keeping Executive'),
			array('id' =>453, 'name' => 'Room Service Manager'),
			array('id' =>454, 'name' => 'Security Manager/Officer'),
			array('id' =>455, 'name' => 'Laundry Manager'),
			array('id' =>456, 'name' => 'Chef/Kitchen Manager'),
			array('id' =>457, 'name' => 'Sous Chef'),
			array('id' =>458, 'name' => 'Travel Agent/Tour Operator'),
			array('id' =>459, 'name' => 'Cashier'),
			array('id' =>460, 'name' => 'Concierge'),
			array('id' =>461, 'name' => 'Chief Engineer'),
			array('id' =>462, 'name' => 'Shift Engineer/Supervisor'),
			array('id' =>463, 'name' => 'Masseur'),
			array('id' =>464, 'name' => 'Attendant'),
			array('id' =>465, 'name' => 'Quality Assurance/Control'),
			array('id' =>466, 'name' => 'GM/DGM'),
			array('id' =>467, 'name' => 'Other Hotels/Restaurants'),
			array('id' =>468, 'name' => 'Airline Cabin Crew'),
			array('id' =>469, 'name' => 'Airline Ground Staff'),
			array('id' =>470, 'name' => 'Manufacturing/Engineering/R&D'),
			array('id' =>471, 'name' => 'Chemical Engineer'),
			array('id' =>472, 'name' => 'Design Manager/Engineer'),
			array('id' =>473, 'name' => 'Electronics/Instrumentation Engineer'),
			array('id' =>474, 'name' => 'Spares Manager/Engineer'),
			array('id' =>475, 'name' => 'Environmental Engineer'),
			array('id' =>476, 'name' => 'Industrial Engineering'),
			array('id' =>477, 'name' => 'Maintenance'),
			array('id' =>478, 'name' => 'Tool Room'),
			array('id' =>479, 'name' => 'Paint Shop'),
			array('id' =>480, 'name' => 'Press Shop'),
			array('id' =>481, 'name' => 'Weld Shop'),
			array('id' =>482, 'name' => 'Foreman'),
			array('id' =>483, 'name' => 'Draughtsman'),
			array('id' =>484, 'name' => 'Machine Operator'),
			array('id' =>485, 'name' => 'Assembler'),
			array('id' =>486, 'name' => 'Floor Supervisor'),
			array('id' =>487, 'name' => 'Workshop Manager'),
			array('id' =>488, 'name' => 'Process Manager/Engineer'),
			array('id' =>489, 'name' => 'Production Manager/Engineer'),
			array('id' =>490, 'name' => 'Projects'),
			array('id' =>491, 'name' => 'Tech/Engg - Manager'),
			array('id' =>492, 'name' => 'R & D Manager'),
			array('id' =>493, 'name' => 'Safety Officer/Engineer'),
			array('id' =>494, 'name' => 'Service Manager/Engineer'),
			array('id' =>495, 'name' => 'Technician'),
			array('id' =>496, 'name' => 'Marine Engineer'),
			array('id' =>497, 'name' => 'Plant Head/Factory Manager'),
			array('id' =>498, 'name' => 'Mines Engineer'),
			array('id' =>499, 'name' => 'Automotive Engineer'),
			array('id' =>500, 'name' => 'Aviation Engineer'),
			array('id' =>501, 'name' => 'Application Engineer'),
			array('id' =>502, 'name' => 'Textile Designer'),
			array('id' =>503, 'name' => 'Apparel Designer'),
			array('id' =>504, 'name' => 'Accessory Designer'),
			array('id' =>505, 'name' => 'Footwear Designer'),
			array('id' =>506, 'name' => 'Jewelry Designer'),
			array('id' =>507, 'name' => 'Packaging'),
			array('id' =>508, 'name' => 'Customer Service/Tech Support'),
			array('id' =>509, 'name' => 'Lab Staff'),
			array('id' =>510, 'name' => 'Research Assistant'),
			array('id' =>511, 'name' => 'Data Management/Statistics'),
			array('id' =>512, 'name' => 'Research Scientist'),
			array('id' =>513, 'name' => 'VP/GM - Engg/Production'),
			array('id' =>514, 'name' => 'VP/GM - R & D (Production & Engg)'),
			array('id' =>515, 'name' => 'VP/GM - Design (Production & Engg)'),
			array('id' =>516, 'name' => 'Other Production/Engineering/R&D'),
			array('id' =>517, 'name' => 'Oil & Gas'),
			array('id' =>518, 'name' => 'Rigger'),
			array('id' =>519, 'name' => 'Fire & gas technician'),
			array('id' =>520, 'name' => 'HVAC expert'),
			array('id' =>521, 'name' => 'Desalination expert'),
			array('id' =>522, 'name' => 'Drilling expert'),
			array('id' =>523, 'name' => 'Gas turbine expert'),
			array('id' =>524, 'name' => 'Petrophysics/Geologist/Seismic Interpretation'),
			array('id' =>525, 'name' => 'Thermal inspector'),
			array('id' =>526, 'name' => 'Safety Engineer'),
			array('id' =>527, 'name' => 'Structural Engineering'),
			array('id' =>528, 'name' => 'Electrical and Instrumentation Engineering'),
			array('id' =>529, 'name' => 'Rotating/Packaging/Static'),
			array('id' =>530, 'name' => 'Engineering - Materials & Corrosion'),
			array('id' =>531, 'name' => 'Engineering - Facilities/Surface'),
			array('id' =>532, 'name' => 'Engineering - Heating and Thermal Equipment'),
			array('id' =>533, 'name' => 'Engineering - Offshore Structures'),
			array('id' =>534, 'name' => 'Engineering - Pipelines'),
			array('id' =>535, 'name' => 'Engineering - Pressure Equipment'),
			array('id' =>536, 'name' => 'Engineering - Reactor & Solids Processing'),
			array('id' =>537, 'name' => 'Engineering - Support'),
			array('id' =>538, 'name' => 'Reservoir Engineering'),
			array('id' =>539, 'name' => 'Well Engineering'),
			array('id' =>540, 'name' => 'Exploration and Production Engineering'),
			array('id' =>541, 'name' => 'Piping Engineering'),
			array('id' =>542, 'name' => 'Mechanical Engineering'),
			array('id' =>543, 'name' => 'SURF Engineers (Subsea Umbilicals, Risers and Flowlines)'),
			array('id' =>544, 'name' => 'Field Engineer'),
			array('id' =>545, 'name' => 'Inspection Engineer'),
			array('id' =>546, 'name' => 'Tank Design Engineering'),
			array('id' =>547, 'name' => 'Process Engineering'),
			array('id' =>548, 'name' => 'Project Engineering'),
			array('id' =>549, 'name' => 'Production & Manufacturing Downstream'),
			array('id' =>550, 'name' => 'QA/QC'),
			array('id' =>551, 'name' => 'FPSO/FSO Conversion Engineer'),
			array('id' =>552, 'name' => 'Process Maintenance Engineer'),
			array('id' =>553, 'name' => 'Risk Assessment Engineer'),
			array('id' =>554, 'name' => 'Reliability Engineer'),
			array('id' =>555, 'name' => 'Subsea - Project'),
			array('id' =>556, 'name' => 'Research & Technology Development'),
			array('id' =>557, 'name' => 'HSE Management Specialist'),
			array('id' =>558, 'name' => 'HSEQ'),
			array('id' =>559, 'name' => 'Gas Commercial Negotiator'),
			array('id' =>560, 'name' => 'Gas Regulators/Planners'),
			array('id' =>561, 'name' => 'Oil Trader/Bunker Trader'),
			array('id' =>562, 'name' => 'Proposal & Estimation'),
			array('id' =>563, 'name' => 'Commissioning'),
			array('id' =>564, 'name' => 'Documentation Controller'),
			array('id' =>565, 'name' => 'Packaging and Product Development'),
			array('id' =>566, 'name' => 'EPC (Engineering, Procurement and Construction)'),
			array('id' =>567, 'name' => 'Refinery Manager/Project Manager'),
			array('id' =>568, 'name' => 'Plant Supervisor'),
			array('id' =>569, 'name' => 'Head - Drilling & Completions'),
			array('id' =>570, 'name' => 'Head - Development & Projects'),
			array('id' =>571, 'name' => 'Head - EPC'),
			array('id' =>572, 'name' => 'VP -Operations/COO'),
			array('id' =>573, 'name' => 'VP/GM - Manufacturing Plant'),
			array('id' =>574, 'name' => 'Other Oil & Gas'),
			array('id' =>575, 'name' => 'Subsea - Installation/System and Controls'),
			array('id' =>576, 'name' => 'Subsea - Pipeline/Flow Assurance'),
			array('id' =>577, 'name' => 'Pharmaceutical/Biotechnology'),
			array('id' =>578, 'name' => 'Clinical Enrollment Manager'),
			array('id' =>579, 'name' => 'Clinical Operations Director'),
			array('id' =>580, 'name' => 'Clinical Operations Manager/Lead'),
			array('id' =>581, 'name' => 'Clinical Project Associate/Manager'),
			array('id' =>582, 'name' => 'Clinical Project Director'),
			array('id' =>583, 'name' => 'Clinical Project Specialist'),
			array('id' =>584, 'name' => 'Clinical Research Associate/Manager'),
			array('id' =>585, 'name' => 'Clinical Research Coordinator/Nurse'),
			array('id' =>586, 'name' => 'Clinical Sites Services Director'),
			array('id' =>587, 'name' => 'Clinical Sites Services Manager/Specialist'),
			array('id' =>588, 'name' => 'Clinical Study Manager'),
			array('id' =>589, 'name' => 'Clinical Team Manager'),
			array('id' =>590, 'name' => 'Clinical Trials Associate/Manager'),
			array('id' =>591, 'name' => 'Feasibility Manager'),
			array('id' =>592, 'name' => 'Proposal & Contracts Specialist/Manager'),
			array('id' =>593, 'name' => 'Study Start-Up Specialist'),
			array('id' =>594, 'name' => 'Agronomist'),
			array('id' =>595, 'name' => 'Analytical Chemist'),
			array('id' =>596, 'name' => 'Biologist'),
			array('id' =>597, 'name' => 'Epidemiology Director'),
			array('id' =>598, 'name' => 'Epidemiology Manager'),
			array('id' =>599, 'name' => 'Food Technologist'),
			array('id' =>600, 'name' => 'Formulation Scientist'),
			array('id' =>601, 'name' => 'Laboratory Technician'),
			array('id' =>602, 'name' => 'Medical Technician'),
			array('id' =>603, 'name' => 'Medicinal Chemist'),
			array('id' =>604, 'name' => 'New Product Development'),
			array('id' =>605, 'name' => 'Pharmacokinetic Scientist'),
			array('id' =>606, 'name' => 'Pharmacovigilance Scientist'),
			array('id' =>607, 'name' => 'Process Development Scientist'),
			array('id' =>608, 'name' => 'R&D Director'),
			array('id' =>609, 'name' => 'Chemical Research Scientist'),
			array('id' =>610, 'name' => 'Drug Regulatory Doctor'),
			array('id' =>611, 'name' => 'Analytical Chemistry Scientist'),
			array('id' =>612, 'name' => 'Toxicologist'),
			array('id' =>613, 'name' => 'Nuclear Medicine'),
			array('id' =>614, 'name' => 'Research Associate'),
			array('id' =>615, 'name' => 'Bio-Technology Research Scientist'),
			array('id' =>616, 'name' => 'Pharmaceutical Research Scientist'),
			array('id' =>617, 'name' => 'Engineering Manager'),
			array('id' =>618, 'name' => 'GMP Auditor'),
			array('id' =>619, 'name' => 'Manufacturing & Supply'),
			array('id' =>620, 'name' => 'Process Engineer'),
			array('id' =>621, 'name' => 'Product Engineer'),
			array('id' =>622, 'name' => 'Production Chemist'),
			array('id' =>623, 'name' => 'Production Manager'),
			array('id' =>624, 'name' => 'Project Engineer'),
			array('id' =>625, 'name' => 'Service Engineer'),
			array('id' =>626, 'name' => 'Quality Director'),
			array('id' =>627, 'name' => 'Operations Director'),
			array('id' =>628, 'name' => 'Goods Manufacturing Practices (GMP)'),
			array('id' =>629, 'name' => 'Quality Control Manager'),
			array('id' =>630, 'name' => 'Technology Transfer Engineer'),
			array('id' =>631, 'name' => 'Regulatory Affairs Director'),
			array('id' =>632, 'name' => 'Regulatory Affairs Executive'),
			array('id' =>633, 'name' => 'Regulatory Affairs Manager'),
			array('id' =>634, 'name' => 'Clinical Research Physician'),
			array('id' =>635, 'name' => 'Drug Safety Officer'),
			array('id' =>636, 'name' => 'Medical Affairs Manager'),
			array('id' =>637, 'name' => 'Medical Director'),
			array('id' =>638, 'name' => 'Medical Science Liasion'),
			array('id' =>639, 'name' => 'Documentation/Medical Writing'),
			array('id' =>640, 'name' => 'Pharmacovigilance Manager'),
			array('id' =>641, 'name' => 'Pharmacovigilance Physician'),
			array('id' =>642, 'name' => 'Clinical GCP Trainer'),
			array('id' =>643, 'name' => 'Quality Assurance Auditor (GXP,GMP)'),
			array('id' =>644, 'name' => 'Quality Assurance Director'),
			array('id' =>645, 'name' => 'Quality Auditor (GCP) Director'),
			array('id' =>646, 'name' => 'Quality Auditor (GCP) Manager'),
			array('id' =>647, 'name' => 'Quality Compliance'),
			array('id' =>648, 'name' => 'Quality Lead/Manager'),
			array('id' =>649, 'name' => 'Practical Training/Internship'),
			array('id' =>650, 'name' => 'Nutritionist/Dietician'),
			array('id' =>651, 'name' => 'Other Pharma'),
			array('id' =>652, 'name' => 'Postdoc Position/Fellowship'),
			array('id' =>653, 'name' => 'HEOR Manager'),
			array('id' =>654, 'name' => 'Analytics/Business Intelligence'),
			array('id' =>655, 'name' => 'Data Analyst'),
			array('id' =>656, 'name' => 'Web Analyst'),
			array('id' =>657, 'name' => 'Financial Analyst'),
			array('id' =>658, 'name' => 'Marketing Analyst'),
			array('id' =>659, 'name' => 'Insurance Analyst'),
			array('id' =>660, 'name' => 'Other Analytics/Business Intelligence'),
			array('id' =>661, 'name' => 'Real Estate'),
			array('id' =>662, 'name' => 'Management Trainee'),
			array('id' =>663, 'name' => 'Interior Designer'),
			array('id' =>664, 'name' => 'Brokerage'),
			array('id' =>665, 'name' => 'Land Development'),
			array('id' =>666, 'name' => 'Property Management'),
			array('id' =>667, 'name' => 'Real Estate Appraising'),
			array('id' =>668, 'name' => 'Real Estate Counseling'),
			array('id' =>669, 'name' => 'Real Estate Research'),
			array('id' =>670, 'name' => 'Other Real Estate'),
			array('id' =>671, 'name' => 'Retail Chains'),
			array('id' =>672, 'name' => 'Area Manager'),
			array('id' =>673, 'name' => 'Regional Manager'),
			array('id' =>674, 'name' => 'Shift Manager'),
			array('id' =>675, 'name' => 'Buyer/Sourcing Manager'),
			array('id' =>676, 'name' => 'Front Desk'),
			array('id' =>677, 'name' => 'Retail Store Manager'),
			array('id' =>678, 'name' => 'Operations Executive/Supervisor'),
			array('id' =>679, 'name' => 'Inventory Control Manager'),
			array('id' =>680, 'name' => 'Loyalty Program'),
			array('id' =>681, 'name' => 'Visual Merchandiser'),
			array('id' =>682, 'name' => 'Loss Prevention Manager'),
			array('id' =>683, 'name' => 'Technical - Manager'),
			array('id' =>684, 'name' => 'GM'),
			array('id' =>685, 'name' => 'Other Retail Chains/Shops'),
			array('id' =>686, 'name' => 'Supply Chain Management'),
			array('id' =>687, 'name' => 'Purchase Clerk'),
			array('id' =>688, 'name' => 'Transportation'),
			array('id' =>689, 'name' => 'Telecom/ISP'),
			array('id' =>690, 'name' => 'RF Planning Engineer'),
			array('id' =>691, 'name' => 'Network Installation & Administration'),
			array('id' =>692, 'name' => 'Network Planning - Chief Engineer'),
			array('id' =>693, 'name' => 'GSM Engineer'),
			array('id' =>694, 'name' => 'Telecom Engineer'),
			array('id' =>695, 'name' => 'RF Installation & Administration Engineer'),
			array('id' =>696, 'name' => 'RF Planning - Chief Engineer'),
			array('id' =>697, 'name' => 'O&M Engineer'),
			array('id' =>698, 'name' => 'Switching - Engineer'),
			array('id' =>699, 'name' => 'Switching - Chief Engineer'),
			array('id' =>700, 'name' => 'System Engineer'),
			array('id' =>701, 'name' => 'System Security - Chief Engineer'),
			array('id' =>702, 'name' => 'Network Planning - Engineer'),
			array('id' =>703, 'name' => 'Customer Support Engineer/Technician'),
			array('id' =>704, 'name' => 'Outside Service Providers'),
			array('id' =>705, 'name' => 'Regional Mgr/Manager(Operations)'),
			array('id' =>706, 'name' => 'VP/Head - Technology (Telecom/ISP)'),
			array('id' =>707, 'name' => 'Other Telecom/ISP'),
			array('id' =>708, 'name' => 'VP/Head - Technology'),
			array('id' =>709, 'name' => 'Travel/Airlines'),
			array('id' =>710, 'name' => 'Reservation and Ticketing'),
			array('id' =>711, 'name' => 'Domestic Travel'),
			array('id' =>712, 'name' => 'International Travel'),
			array('id' =>713, 'name' => 'Documentaion & VISA'),
			array('id' =>714, 'name' => 'Air Hostess/Steward/Cabin Crew'),
			array('id' =>715, 'name' => 'Pilot'),
			array('id' =>716, 'name' => 'Ground Staff'),
			array('id' =>717, 'name' => 'Office Assistant'),
			array('id' =>718, 'name' => 'Branch Head'),
			array('id' =>719, 'name' => 'Other Travel/Airlines'),
			array('id' =>720, 'name' => 'Entrepreneur'),
			array('id' =>721, 'name' => 'Fashion Designer'),
			array('id' =>722, 'name' => 'Fitness Trainer'),
			array('id' =>723, 'name' => 'Horticulturist'),
			array('id' =>724, 'name' => 'Model'),
			array('id' =>725, 'name' => 'Painter'),
			array('id' =>726, 'name' => 'Security Officer'),
			array('id' =>727, 'name' => 'Statistician'),
			array('id' =>728, 'name' => 'Electrician'),
			array('id' =>729, 'name' => 'Driver/Chauffeur'),
			array('id' =>730, 'name' => 'Beautician'),
			array('id' =>731, 'name' => 'Language Expert'),
			array('id' =>732, 'name' => 'AC Technician'),
			array('id' =>733, 'name' => 'Jewellery Designer'),
			array('id' =>734, 'name' => 'Other Roles'),
			array('id' =>735, 'name' => 'Teacher/Lecturer/Professor'),

        );

        DB::table("functional_roles")->insert($data);
    }
}
